### ISSUE TITLE
Can we get a csv with "," instead of ";" as separators?

### ISSUE THREAD

**Issue by derwas** [LOS-ESSnet/Paris-Hackathon#2]

**Comment by derwas** [comment]
The issue is with [SILC FR dataset](https://github.com/LOS-ESSnet/Paris-Hackathon/blob/master/data/silc-fr.md)

**Comment by derwas** [comment]
Hey @ThomasPO for the moment, let's replace ";" by "," and we will have the discussion about the "Total" during the hackathon.

**Comment by ThomasPO** [comment]
@derwas 
Fixed. Issue closed
